### ISSUE TITLE
Adding new chain

### ISSUE THREAD

**Issue by jimango** [valamidev/web3-defi-honeypot-and-slippage-checker#10]
Hello :)

Im looking into how to make this work for Alveychain, a new blockchain. https://alveyscan.com/

And im not 100% familiar with how to mod this. 
If you would be able to help me with this it eould be very much appreciated:)

If you need any information or want to talk to me feel free to write me :)

**Comment by valamidev** [comment]
Usually deploying this contract will work:

https://github.com/valamidev/web3-defi-honeypot-and-slippage-checker/blob/main/contract/honeychecker.sol

It depend on the Swap Router contract does it need any modification or not.

**Comment by jimango** [comment]
The swap router address is 0x154a76D1095c69a942411CaB9aEef6a155EbF90E

So i just replace this?
![Screenshot_20230103_092123_Vivaldi Browser](https://user-images.githubusercontent.com/15493416/210321353-c71ee4b1-aebc-4bba-a47b-c5373d54a2dc.jpg)

**Comment by jimango** [comment]
![Screenshot_20230103_092123_Vivaldi Browser](https://user-images.githubusercontent.com/15493416/210322110-02085a0f-8518-4b62-824d-fa310ec1d6c2.jpg)
 What does this code do?

Will i need to replace it?
Or is it enough to add the router address for our chainDEX 0x154a76D1095c69a942411CaB9aEef6a155EbF90E 
Similar like with the other chains in the code?

**Comment by valamidev** [comment]
> 

approveInfinity is need for the swapSimulation, you can only sell token which is approved, it is not harmful as these methods never actually executed on the blockchain.

You do not need to change anything in the contract code.
