### ISSUE TITLE
Can you add a AddLiquidity event ?

### ISSUE THREAD

**Issue by tsarbuig** [valamidev/web3-defi-honeypot-and-slippage-checker#11]
Hey bro, thanks for this great work.

I'm trying to use this honeypot checker on a Sniper bot, but it fails when we use is on same block as AddLiquidity Tx

Since this  AddLiquidity Tx is not mined yet, swap ends in error, so the token is falsely considered as a honeypot

--> is there a way to create an AddLiquidity event in the smart contract, so as it adds himself liquidity and it could work on a Sniper bot ?

Thanks a lot

**Comment by valamidev** [comment]
Yes, there is a way but that is much more complicated and need inline assembly magic.

**Comment by tsarbuig** [comment]
oh wow, ok 

Do you know if, even without that, we can use your smart contract to test token taxes when sniping token on same block as AddLiquidity event?

**Comment by valamidev** [comment]
> oh wow, ok
> 
> Do you know if, even without that, we can use your smart contract to test token taxes when sniping token on same block as AddLiquidity event?

No, this contract only work if the chain already has booked liquidity data.
