### ISSUE TITLE
Could you add for Arbitrum Sushiswap?

### ISSUE THREAD

**Issue by Nonym000** [valamidev/web3-defi-honeypot-and-slippage-checker#12]
Hi!

First of all. Thank you for sharing this code with us. Its working fine for me on ethereum and ive been trying to make it work on Arbitrum Sushiswap. Somehow, all my simulation fails. Would you be kind to test/make it work there as well?

Would be much appreciated. Thanks!

**Comment by valamidev** [comment]
Hi,

yes, I will make a small structure change in the repository aswel to point out what have to be changed in the contract to ensure compatibility with a Swap Router.

**Comment by Nonym000** [comment]
Thank you!

**Comment by valamidev** [comment]
This should work once it is deployed:

https://github.com/valamidev/web3-defi-honeypot-and-slippage-checker/blob/main/contract/arbitrum/sushiswapChecker.sol

**Comment by dajiba112** [comment]
Does this tell the honeypot used to attack ARB?
