### ISSUE TITLE
Check fail on several tokens

### ISSUE THREAD

**Issue by BrokedTV** [valamidev/web3-defi-honeypot-and-slippage-checker#4]
The test fail (return HP - transfer failed) on several tokens, where on others check site they are correctly reported with the right taxes.

Example: bsc 0x3f203c1403ce39d4d42c4667287a7fb2b1db1066

**Comment by valamidev** [comment]
> The test fail (return HP - transfer failed) on several tokens, where on others check site they are correctly reported with the right taxes.
> 
> Example: bsc 0x3f203c1403ce39d4d42c4667287a7fb2b1db1066

Binance Chain is not supported by this repo, for Binance there are better alternatives.

**Comment by BrokedTV** [comment]
> > The test fail (return HP - transfer failed) on several tokens, where on others check site they are correctly reported with the right taxes.
> > Example: bsc 0x3f203c1403ce39d4d42c4667287a7fb2b1db1066
> 
> Binance Chain is not supported by this repo, for Binance there are better alternatives.

Why it should not be supported? is there any tech difference from other chains?
The same tested contract i posted above deployed on a supported chain will still fail.

**Comment by valamidev** [comment]
Because there is community accepted Tax/Honeypot checker for BSC network which is the `https://honeypot.is` . 

This repo is made to make an universal contract for chains where is no other alternative. Feel free to deploy to BSC.

**Comment by BrokedTV** [comment]
> Because there is community accepted Tax/Honeypot checker for BSC network which is the `https://honeypot.is` .
> 
> This repo is made to make an universal contract for chains where is no other alternative. Feel free to deploy to BSC.

I did deploy on BSC to test the success rate of the tester vs other popular tester, as the one you pointed out, and that's how i realized that the current version show several tokens as Honeypot when they are not, and that is what i was reporting . 
 The same token contract if forked on a chain you directly support will still fail the check, no matter what the chain it is deployed on.

**Comment by valamidev** [comment]
> The same token contract if forked on a chain you directly support will still fail the check, no matter what the chain it is deployed on.

Please give some example, we are using this contract and not experienced false report unless the contract / LP has some issue.

**Comment by BrokedTV** [comment]
The contract i posted on the first post, the check for that CA succeed on ishoneypot but fail with the contract from this repo

0x3f203c1403ce39d4d42c4667287a7fb2b1db1066

**Comment by valamidev** [comment]
> The contract i posted on the first post, the check for that CA succeed on ishoneypot but fail with the contract from this repo
> 
> 0x3f203c1403ce39d4d42c4667287a7fb2b1db1066

There is no BSC support in this repo, so it is expected that it will fail.

**Comment by BrokedTV** [comment]
> > The contract i posted on the first post, the check for that CA succeed on ishoneypot but fail with the contract from this repo
> > 0x3f203c1403ce39d4d42c4667287a7fb2b1db1066
> 
> There is no BSC support in this repo, so it is expected that it will fail.

I deployed your contract checker on BSC and it fail with it.
You can fork 0x3f203c1403ce39d4d42c4667287a7fb2b1db1066 on your favorite chain or testnet and check on that if you prefer, i don't see why the results should be any different

**Comment by valamidev** [comment]
Okay, I deployed the contract for you:

0x3f203c1403ce39d4d42c4667287a7fb2b1db1066 

`BSC MainNet {
  buyTax: 14.999999788758412,
  sellTax: 13.279372300708047,
  buyGasCost: '153334',
  sellGasCost: '296250',
  isHoneypot: 0
}`

**Comment by BrokedTV** [comment]
It's working fine you are right, i realized that i was testing with a 2 BNB buy which was too much for that token, that was the only reason why it was returning 
buyTax: -1, sellTax: -1, isHoneypot: 1, error: Error: Returned error: execution reverted: Pancake: TRANSFER_FAIL
great and gj!
