### ISSUE TITLE
Every contract is honeypot on DogeChain

### ISSUE THREAD

**Issue by alchemist0803** [valamidev/web3-defi-honeypot-and-slippage-checker#8]
Thanks for your checker.
I tried to use your checker file in dogechain.
But every token throw honey error and returns ishoneypot = 1.
I used your sample on dogechain. Just changed token address.

What can be a problem? How can I call doge contract?

**Comment by valamidev** [comment]
Could be 3 thing:
- recently Dogechain RPC is supper unreliable 
- A fact that 90%+ of the Dogechain tokens are honeypot, only a dozen legit Token/Wdoge pair exists.
- Use other test address with higher balance than it has in the example.

**Comment by valamidev** [comment]
I made some update on the DogeSwap checker contract that had some issues:

https://github.com/valamidev/web3-defi-honeypot-and-slippage-checker/commit/0b871e69bff5995f2ec42589fef40b72520438db

**Comment by alchemist0803** [comment]
Thanks.
It is working now.
Updated one works fine.
I am looking for your next amazing one.

Regards.
