### ISSUE TITLE
Sell tax is not correct

### ISSUE THREAD

**Issue by Jeko83** [valamidev/web3-defi-honeypot-and-slippage-checker#9]
I noticed that the sell tax is not correct.
Why not use getAmountsOur also on the sell part of things? 
By checking only for the WETH remaming in the wallet at the end of the transaction, I can only get slippage + sell tax, not sell tax alone (sell side).
This makes it impossible for me to get the true sell tax.
Amazing work btw

**Comment by valamidev** [comment]
Yes, but that was designed to be like this. There is no swap without slippage included, so this output can be used to set minimumReceived without any other calculation. 
You reduce the slippage effect on the Sell Tax result with using a relatively small amount of WETH as input.
